spring:
  ai:
    mcp:
      client:
        enabled: true
        stdio:
          connections:
            github:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - GITHUB_PERSONAL_ACCESS_TOKEN
                - -e
                - GITHUB_TOOLSETS
                - ghcr.io/github/github-mcp-server
              env:
                GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN:}
                GITHUB_TOOLSETS: ${GITHUB_TOOLSETS:repos,issues,pull_requests,users}

lumisight:
  mcp:
    tools:
      name-prefix: mcp_github_
